version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: my_mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ecommerce_system
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  order-service:
    build:
      context: ./Order Service
      dockerfile: Dockerfile
    container_name: order-service
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development

  customer-service:
    build:
      context: ./Customer Service
      dockerfile: Dockerfile
    container_name: customer-service
    ports:
      - "5002:5000"
    environment:
      - FLASK_ENV=development
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=ecommerce_system
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
    depends_on:
      - mysql

  inventory-service:
    build:
      context: ./Inventory Service
      dockerfile: Dockerfile
    container_name: inventory-service
    ports:
      - "5003:5000"
    environment:
      - FLASK_ENV=development
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=ecommerce_system
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
    depends_on:
      - mysql

  notification-service:
    build:
      context: ./Notification Service
      dockerfile: Dockerfile
    container_name: notification-service
    ports:
      - "5004:5000"
    environment:
      - FLASK_ENV=development
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=ecommerce_system
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
    depends_on:
      - mysql

  pricing-service:
    build:
      context: ./Pricing Service
      dockerfile: Dockerfile
    container_name: pricing-service
    ports:
      - "5005:5000"
    environment:
      - FLASK_ENV=development
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=ecommerce_system
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
    depends_on:
      - mysql
